export type CourseId = "kids" | "beginner" | "professional" | "women" | "exam";
export type Course = { id: CourseId; title: string; ur: string; short: string; overview: string; audience: string[]; outcomes: string[]; topics: string[]; format: string[] };
export const courseDetails: Course[] = [
{id:"kids",title:"Kids English",ur:"بچوں کے لیے انگلش",short:"Fun, confidence-building speaking practice for young learners.",overview:"A friendly, activity-based English course that helps children speak naturally, understand everyday English and enjoy learning without pressure.",audience:["School-age children","Young learners who need speaking confidence","Children starting English from the basics"],outcomes:["Speak simple sentences with confidence","Build useful everyday vocabulary","Improve listening and pronunciation","Use English in real-life situations"],topics:["Greetings & introductions","Everyday conversation","Vocabulary through activities","Pronunciation & listening","Stories, questions and answers"],format:["1-to-1 online classes","One-hour flexible slots","Personalised activities","Free demo before enrolment"]},
{id:"beginner",title:"Beginner English",ur:"Beginners کے لیے انگلش",short:"Build your basics, vocabulary and everyday speaking confidence.",overview:"A step-by-step foundation for learners who want to stop translating every sentence and start communicating in practical English.",audience:["Complete beginners","Students with basic English knowledge","Learners who understand English but hesitate to speak"],outcomes:["Form correct everyday sentences","Use core grammar naturally","Grow practical vocabulary","Speak in common daily situations"],topics:["Sentence building","Present, past & future basics","Questions and answers","Common vocabulary","Prepositions & connectors","Speaking drills"],format:["1-to-1 online classes","One-hour flexible slots","Personalised practice","Free demo before enrolment"]},
{id:"professional",title:"Professional English",ur:"پروفیشنل انگلش",short:"Meetings, interviews, workplace communication and polished speaking.",overview:"Practical workplace English for people who want clearer communication in interviews, meetings, presentations and professional conversations.",audience:["University students","Job seekers","Working professionals","Freelancers and business owners"],outcomes:["Speak clearly in professional settings","Handle interviews with confidence","Participate in meetings","Present ideas in structured English","Improve professional vocabulary"],topics:["Interview English","Meetings & discussions","Presentations","Email and workplace language","Professional small talk","Fluent responses"],format:["1-to-1 online classes","One-hour flexible slots","Goal-based lessons","Free demo before enrolment"]},
{id:"women",title:"English for Women",ur:"خواتین کے لیے انگلش",short:"A comfortable, supportive learning environment designed for women.",overview:"A supportive speaking program focused on practical communication, confidence and a comfortable learning environment for women.",audience:["Women returning to learning","Students and mothers","Women preparing for work or study","Learners who prefer a women-focused environment"],outcomes:["Speak more confidently in daily life","Improve conversation skills","Build useful vocabulary","Communicate in study and work settings"],topics:["Daily conversation","Confidence building","Social English","Study & workplace communication","Vocabulary and pronunciation","Practical speaking practice"],format:["1-to-1 online classes","One-hour flexible slots","Supportive instruction","Free demo before enrolment"]},
{id:"exam",title:"IELTS · TOEFL · PTE · IGCSE",ur:"IELTS · TOEFL · PTE · IGCSE",short:"Focused preparation, exam strategy and practice for your target test.",overview:"Targeted English and exam preparation designed around your selected test, current level and goals, with focused practice and feedback.",audience:["IELTS candidates","TOEFL candidates","PTE candidates","IGCSE English students"],outcomes:["Understand your exam format","Improve speaking and language performance","Practice with targeted tasks","Identify weak areas and improve them","Build an exam-focused study routine"],topics:["Speaking practice","Reading & listening strategies","Writing structure","Vocabulary & grammar","Timed practice","Feedback and correction"],format:["1-to-1 online classes","One-hour flexible slots","Targeted exam practice","Free demo before enrolment"]}
];
