import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { z } from "zod";
import { courseDetails } from "../lib/course-data";
export const Route = createFileRoute("/courses/$courseId")({ component: CourseDetail, validateSearch: z.object({ lang: z.enum(["en","ur"]).catch("en") }) });
function CourseDetail(){
 const {courseId}=Route.useParams(); const {lang="en"}=Route.useSearch(); const course=courseDetails.find(x=>x.id===courseId)||courseDetails[0]; const [name,setName]=useState(""); const navigate=useNavigate(); const isUr=lang==="ur"; const title=isUr?course.ur:course.title;
 const openDemo=()=>{navigate({to:"/",hash:"enroll"});setTimeout(()=>document.getElementById("enroll")?.scrollIntoView({behavior:"smooth"}),120)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();const m=`*Speak Right — Free Demo Request*\nName: ${name}\nDesired course: ${course.title}`;window.open(`https://wa.me/923706440824?text=${encodeURIComponent(m)}`,"_blank")};
 return <div className={`coursePage ${isUr?"urdu":""}`} dir={isUr?"rtl":"ltr"}><header className="courseNav"><Link to="/" className="detailBrand"><img src="/speak-right-logo.jpg" alt="Speak Right logo"/><span><strong>Speak Right</strong><small>ENGLISH SPOKEN ACADEMY</small></span></Link><div className="detailActions"><Link to="/courses/$courseId" params={{courseId:course.id}} search={{lang:isUr?"en":"ur"}}>{isUr?"English":"اردو"}</Link><button onClick={openDemo}>{isUr?"فری ڈیمو":"Book free demo"}</button></div></header>
 <main className="detailMain"><Link to="/" hash="courses" className="back">← {isUr?"تمام کورسز":"All courses"}</Link>
 <section className="detailHero"><div><div className="eyebrow"><i/> {isUr?"آپ کے مقصد کے لیے مخصوص کورس":"A focused learning path"}</div><h1>{title}</h1><p>{course.overview}</p><button className="primary" onClick={openDemo}>{isUr?"فری ڈیمو بک کریں":"Book your free demo"}<span>↗</span></button></div><div className="detailStamp"><strong>1-to-1</strong><span>ONLINE<br/>LEARNING</span><em>FREE DEMO</em></div></section>
 <section className="detailGrid"><div className="detailCard"><small>{isUr?"یہ کورس کس کے لیے ہے":"WHO IT'S FOR"}</small><h2>{isUr?"آپ یہاں سے شروع کر سکتے ہیں":"Built around your starting point."}</h2><ul>{course.audience.map(x=><li key={x}>✓ {x}</li>)}</ul></div><div className="detailCard dark"><small>{isUr?"آپ کیا سیکھیں گے":"WHAT YOU'LL BUILD"}</small><h2>{isUr?"حقیقی گفتگو میں اعتماد":"Confidence you can use."}</h2><ul>{course.outcomes.map(x=><li key={x}>✓ {x}</li>)}</ul></div></section>
 <section className="detailSection"><div><div className="eyebrow">{isUr?"کورس کا مواد":"Course focus"}</div><h2>{isUr?"کلاس میں کیا ہوگا؟":"What you'll work on"}</h2></div><div className="topicGrid">{course.topics.map((x,i)=><div key={x}><b>0{i+1}</b><strong>{x}</strong><span>{isUr?"عملی مشق اور instructor feedback":"Practical exercises and instructor feedback."}</span></div>)}</div></section>
 <section className="formatBar"><div><small>{isUr?"فارمیٹ":"FORMAT"}</small><h2>{isUr?"سادہ، ذاتی اور flexible":"Simple. Personal. Flexible."}</h2></div><div className="formatItems">{course.format.map(x=><span key={x}>✓ {x}</span>)}</div></section>
 <section className="detailCta"><div><div className="eyebrow">{isUr?"پہلے کلاس آزمائیں":"Try it first"}</div><h2>{isUr?"فری ڈیمو سے شروع کریں۔":"See the class before you commit."}</h2><p>{isUr?"کلاس پسند آئے تو پھر regular lessons شروع کریں۔":"Attend a real 1-to-1 session, then continue only if it feels right for you."}</p></div><form onSubmit={submit}><input required value={name} onChange={e=>setName(e.target.value)} placeholder={isUr?"آپ کا نام":"Your name"}/><button className="submit">{isUr?"WhatsApp پر ڈیمو بک کریں":"Book demo on WhatsApp"}<span>↗</span></button></form></section>
 </main><a className="whatsapp" href="https://wa.me/923706440824" target="_blank">◔ <b>WhatsApp</b></a><button className="floatingEnroll" onClick={openDemo}>{isUr?"ابھی داخل ہوں":"Enroll now"} <span>↗</span></button></div>;
}
